version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
    - 8082:8082
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    ports:
    - 3307:3306
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234